create table customers
(
customer_id  number(10) GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
user_name  VARCHAR2(20) NOT NULL,
password VARCHAR2(20) NOT NULL,
 first_name VARCHAR(20) NOT NULL,
 last_name VARCHAR2(20) NOT NULL,
address VARCHAR2(50) NOT NULL,
 phone NUMBER(10) NOT NULL,
  email VARCHAR2(20) unique); 
 create sequence seq_customersid
minvalue  1
start with 1
increment by 1
cache 20;
 CREATE table orders
 (
 order_id NUMBER(4) GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
 customer_id NUMBER(4) NOT NULL,
 status VARCHAR2(20) default 'processing',
 order_date date default sysdate,
 foreign key (customer_id)REFERENCES customers(customer_id));
 create table cart
 (
 order_id NUMBER(4) NOT NULL,
 product_id number(4)NOT NULL,
 quantity NUMBER(3) NOT NULL,
 price number(10),
 FOREIGN key (product_id)REFERENCES products(products_id),
 foreign key (order_id)REFERENCES orders(order_id)
 );
--DROP TABLE order_items cascade constraints;
  --DROP TABLE orders cascade constraints;
 CREATE table products
 (
 products_name VARCHAR(20) NOT NULL,
 products_id NUMBER(4) GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
 standard_cost number(10) NOT NULL);